#!/usr/bin/env node
// MACO skill mirror.
//
// Source of truth:  plugins/maco/skills/<name>/
// Mirror:           .agents/skills/<name>/
//
// Why: Claude Code loads `skills/` from inside a plugin directory, and nothing
// else. Every other host we target - OpenCode, Copilot (CLI, cloud agent, code
// review), VS Code agent mode, Codex CLI and Antigravity - reads
// `.agents/skills/`, the agentskills.io neutral path. So one copy lands the
// plugin in 6 of 6 hosts instead of 1 of 6.
//
// Copies, never symlinks: symlinks on Windows need elevation or developer
// mode, and a marketplace consumer on Windows should not have to think about
// that.
//
// The mirror is a VERBATIM copy of the source with a provenance banner inserted
// *inside* the YAML frontmatter. Two rules make that safe:
//
//   1. The banner goes after the opening `---`, never before it. Frontmatter
//      that does not start at byte 0 is not frontmatter: strict parsers
//      (gray-matter and friends) require the file to open with `---` and will
//      silently treat a `#` comment header as body, leaving the skill with no
//      name and no description and therefore no trigger on any host.
//
//   2. The body and every frontmatter field are copied byte for byte. The
//      mirror never re-serialises frontmatter, so `license`, `compatibility`,
//      `metadata` and multi-line descriptions cannot be dropped or mangled by
//      a regex that guessed where a value ended.
//
//   node scripts/sync-skills.mjs           write the mirror
//   node scripts/sync-skills.mjs --check   exit 1 if the mirror is stale

import { readdir, readFile, writeFile, rm, mkdir, stat, cp } from "node:fs/promises"
import { existsSync } from "node:fs"
import { join, dirname, basename } from "node:path"
import { fileURLToPath } from "node:url"

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..")
const SRC = join(ROOT, "plugins", "maco", "skills")
const DEST = join(ROOT, ".agents", "skills")
const CHECK_ONLY = process.argv.includes("--check")

/** Normalise line endings so a CRLF checkout does not read as drift. */
const lf = (s) => s.replace(/\r\n/g, "\n")

/**
 * Extract the YAML frontmatter block. Returns { fm, body } or null.
 * Anchored at byte 0 on purpose - see rule 1 above.
 */
function splitFrontmatter(raw) {
  const m = lf(raw).match(/^---\n([\s\S]*?)\n---(?:\n([\s\S]*))?$/)
  if (!m) return null
  return { fm: m[1], body: m[2] ?? "" }
}

/**
 * Read one top-level scalar out of a frontmatter block.
 *
 * Lenient by design: it exists to validate, not to generate. It handles
 * multi-line (indented continuation) values so a folded description is read as
 * one value instead of truncating at the first line that looks like a key.
 */
function field(fm, key) {
  const lines = fm.split("\n")
  const re = new RegExp(`^${key}:[ \\t]*(.*)$`)
  const start = lines.findIndex((l) => re.test(l))
  if (start === -1) return null
  // Take the capture group. Do not `replace(re, "")` to strip the prefix: the
  // regex spans the whole line, so replacing removes the value along with it.
  let out = (re.exec(lines[start])?.[1] ?? "").trim()
  for (let i = start + 1; i < lines.length; i++) {
    if (/^[ \t]+\S/.test(lines[i])) out += " " + lines[i].trim()
    else break
  }
  out = out.trim()
  if (
    (out.startsWith('"') && out.endsWith('"') && out.length > 1) ||
    (out.startsWith("'") && out.endsWith("'") && out.length > 1)
  ) {
    out = out.slice(1, -1)
  }
  return out || null
}

/** Provenance banner, emitted as YAML comments inside the frontmatter block. */
function banner(skillName) {
  return [
    "# Generated by scripts/sync-skills.mjs - do not edit by hand.",
    `# Source of truth: plugins/maco/skills/${skillName}/`,
    "# Run `npm run sync` after editing the source, and `npm run check` in CI.",
  ].join("\n")
}

/** Build the mirrored SKILL.md: source, verbatim, with the banner injected. */
function render(raw, skillName) {
  const parts = splitFrontmatter(raw)
  if (!parts) return null
  return `---\n${banner(skillName)}\n${parts.fm}\n---\n${parts.body}`
}

async function skillDirs(dir) {
  const entries = await readdir(dir, { withFileTypes: true })
  return entries.filter((e) => e.isDirectory() && !e.name.startsWith(".")).map((e) => e.name)
}

async function walk(dir, base = dir) {
  const out = []
  for (const e of await readdir(dir, { withFileTypes: true })) {
    if (e.name.startsWith(".") || e.name === "node_modules") continue
    const full = join(dir, e.name)
    if (e.isDirectory()) out.push(...(await walk(full, base)))
    else out.push(full.slice(base.length + 1).split(/[\\/]/).join("/"))
  }
  return out.sort()
}

async function main() {
  if (!existsSync(SRC)) {
    console.error(`sync-skills: source directory not found: ${SRC}`)
    process.exit(1)
  }

  const names = (await skillDirs(SRC)).sort()
  if (names.length === 0) {
    console.error("sync-skills: no skills found in plugins/maco/skills/")
    process.exit(1)
  }

  const problems = []
  const written = []
  const unchanged = []
  const extras = []

  for (const name of names) {
    const srcDir = join(SRC, name)
    const destDir = join(DEST, name)
    const skillFile = join(srcDir, "SKILL.md")

    let raw
    try {
      raw = lf(await readFile(skillFile, "utf8"))
    } catch {
      problems.push(`${name}: missing SKILL.md`)
      continue
    }

    const parts = splitFrontmatter(raw)
    if (!parts) {
      problems.push(`${name}: no YAML frontmatter opening at byte 0 (agentskills.io requires it)`)
      continue
    }

    // Validate what we are about to mirror, so a broken source fails here
    // rather than shipping to five hosts.
    const declared = field(parts.fm, "name")
    const desc = field(parts.fm, "description")
    if (!declared) problems.push(`${name}: frontmatter is missing \`name\``)
    else if (declared !== name) problems.push(`${name}: frontmatter name "${declared}" != directory "${name}"`)
    if (!desc) problems.push(`${name}: frontmatter is missing \`description\``)
    if (problems.length) continue

    // Every non-SKILL.md file in the skill (references/, scripts/, assets/)
    // is mirrored verbatim. The agentskills.io spec defines those directories;
    // ignoring them would ship a skill whose instructions point at files the
    // host cannot find.
    const sidecars = (await walk(srcDir)).filter((f) => f !== "SKILL.md")
    for (const f of sidecars) extras.push(`${name}/${f}`)

    const files = [{ rel: "SKILL.md", content: render(raw, name) }, ...sidecars.map((rel) => ({ rel, sidecar: true }))]

    for (const f of files) {
      const dest = join(destDir, f.rel)
      if (f.sidecar) {
        const content = lf(await readFile(join(srcDir, f.rel), "utf8"))
        if (CHECK_ONLY) {
          const current = existsSync(dest) ? lf(await readFile(dest, "utf8")) : null
          if (current !== content) written.push(`${name}/${f.rel}`)
        } else {
          await mkdir(dirname(dest), { recursive: true })
          await writeFile(dest, content, "utf8")
          written.push(`${name}/${f.rel}`)
        }
        continue
      }
      if (CHECK_ONLY) {
        const current = existsSync(dest) ? await readFile(dest, "utf8") : null
        if (current === f.content) unchanged.push(name)
        else written.push(name)
      } else {
        await mkdir(destDir, { recursive: true })
        await writeFile(dest, f.content, "utf8")
        written.push(name)
      }
    }
  }

  // A skill deleted from the source but still present in the mirror is a ghost
  // that continues to load on every host, so it has to be removed.
  if (existsSync(DEST)) {
    for (const name of await skillDirs(DEST)) {
      if (!names.includes(name)) {
        problems.push(`${name}: exists in .agents/skills/ but not in plugins/maco/skills/`)
        if (!CHECK_ONLY) await rm(join(DEST, name), { recursive: true, force: true })
      }
    }
  }

  if (problems.length) {
    console.error("sync-skills: problems\n")
    for (const p of problems) console.error(`  - ${p}`)
    process.exit(1)
  }

  if (CHECK_ONLY) {
    if (written.length) {
      console.error(`sync-skills: mirror is stale for ${written.length} file(s):`)
      for (const w of [...new Set(written)]) console.error(`  - ${w}`)
      console.error("run: npm run sync")
      process.exit(1)
    }
    console.log(`sync-skills: mirror in sync (${unchanged.length} skills, ${extras.length} sidecar files)`)
    return
  }

  const uniqueWritten = [...new Set(written)]
  console.log(`sync-skills: mirrored ${names.length} skill(s) to .agents/skills/`)
  for (const n of uniqueWritten) console.log(`  + ${n}`)
  if (extras.length) {
    console.log(`  (${extras.length} sidecar file(s) mirrored verbatim)`)
    for (const e of extras) console.log(`    . ${e}`)
  }
}

main().catch((err) => {
  console.error("sync-skills:", err.message)
  process.exit(1)
})
